trigger:
- main

pool:
  name: Default   # ✅ self-hosted agent

variables:
  azureServiceConnectionId: 'Azure-Conn'
  functionAppName: 'sc-ticket-backend'
  workingDirectory: '$(System.DefaultWorkingDirectory)/ticket-booking-project/backend'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  workingDirectory: $(workingDirectory)
  displayName: 'Install dependencies'

- task: ArchiveFiles@2
  displayName: 'Archive project'
  inputs:
    rootFolderOrFile: '$(workingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
    replaceExistingArchive: true

# ✅ Better deployment task
- task: AzureFunctionApp@2
  displayName: 'Deploy to Azure Function'
  inputs:
    azureSubscription: '$(azureServiceConnectionId)'
    appType: 'functionAppLinux'
    appName: '$(functionAppName)'
    package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'