trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnectionId: 'Azure-Conn'   # 🔁 your RM connection
  functionAppName: 'sc-ticket-backend'
  workingDirectory: '$(System.DefaultWorkingDirectory)/folder1/backend'   # 🔁 CHANGE THIS

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  workingDirectory: $(workingDirectory)
  displayName: 'Install dependencies'

- task: ArchiveFiles@2
  displayName: 'Archive project'
  inputs:
    rootFolderOrFile: '$(workingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
    replaceExistingArchive: true

- task: AzureFunctionApp@1
  displayName: 'Deploy to Azure Function'
  inputs:
    azureSubscription: '$(azureServiceConnectionId)'
    appType: 'functionAppLinux'
    appName: '$(functionAppName)'
    package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'